LIBNAME = ../../out/staticLibs/shellEffects
OBJDIR = ../../out/obj/shellEffects
TOCLEAN = $(LIBNAME) testProg testProg.dSYM

include ../../common.mk

test: 
	make
	gcc testProg.c -o testProg -ggdb -lncurses ../../out/staticLibs/shellEffects.a -O3 -D MAKE_TEST_PROGRAM

run:
	./testProg

# DO NOT DELETE

../../out/obj/shellEffectseffectFireworks.o: shellEffectsInternal.h
../../out/obj/shellEffectseffectFireworks.o: shellEffects.h shellRenderer.h
../../out/obj/shellEffectseffectLeftRight.o: shellEffectsInternal.h
../../out/obj/shellEffectseffectLeftRight.o: shellEffects.h shellRenderer.h
../../out/obj/shellEffectseffectRunCommand.o: shellEffectsInternal.h
../../out/obj/shellEffectseffectRunCommand.o: shellEffects.h shellRenderer.h
../../out/obj/shellEffectseffectTravelingSprite.o: shellEffectsInternal.h
../../out/obj/shellEffectseffectTravelingSprite.o: shellEffects.h
../../out/obj/shellEffectseffectTravelingSprite.o: shellRenderer.h
../../out/obj/shellEffectseffectUpDown.o: shellEffectsInternal.h
../../out/obj/shellEffectseffectUpDown.o: shellEffects.h shellRenderer.h
../../out/obj/shellEffectsshellEffects.o: shellEffectsInternal.h
../../out/obj/shellEffectsshellEffects.o: shellEffects.h shellRenderer.h
../../out/obj/shellEffectsshellEffects.o: shellEngine.h
../../out/obj/shellEffectsshellEngine.o: shellEngine.h shellEffectsInternal.h
../../out/obj/shellEffectsshellEngine.o: shellEffects.h shellRenderer.h
../../out/obj/shellEffectsshellEngine.o: shellCrazyList.h
../../out/obj/shellEffectsshellRenderer.o: shellRenderer.h
../../out/obj/shellEffectsshellRenderer.o: shellEffectsInternal.h
../../out/obj/shellEffectsshellRenderer.o: shellEffects.h
